### ISSUE TITLE
Use this code in TMeshObject 

### ISSUE THREAD

**Issue by Kline777** [neurolabusc/Fast-Quadric-Mesh-Simplification-Pascal-#1]
Hi!
I was wondering if one could use this code in a GLScene TMeshObject.
If you have some code, could you share it?

I have tried to adapt your demo code, but i think im feed the vertices and faces array wrong because  the end result is a damaged part.

Thanks

**Comment by neurolabusc** [comment]
I would be happy to help. Any hints on how to install GLScene on Lazarus 1.6 for Windows? It seems like a lot of the GLScene for Lazarus documentation is out of date or incorrect. Here are my attempts at getting GLScene to work:

1.) I followed the instructions here http://wiki.freepascal.org/GLScene
  svn co http://svn.freepascal.org/svn/fpcprojects/glscene/trunk glscene
  Checked out revision 2702
copied the global links but Lazarus complains it can not build this old version.

2.) I tried to get the latest trunk
 svn co https://svn.code.sf.net/p/glscene/code/trunk/
 Checked out revision 6906
But this version only seems to be for Delphi (no LPK files)

3.) I downloaded GLScene_v1.4_for_Lazarus.7z from https://sourceforge.net/projects/glscene/files/GLScene/GLScene%20v1.4/
 I tried to follow the instructions to copy the files into my Lazarus and System folders as best as I could, but did not understand what was meant by "Setup Library Paths in Options dialog. Add the directory ../GLSceneLCL/Source" - do they mean that for each project I need to set the Project/ProjectOptions/CompilerOptions/Paths or is there some more general library path for all projects? In any case, I did the former since I do not know how to do the latter. After I recompiled Lazarus I could see GLScene components in the Lazarus toolbar, and was able to open up sample projects like "Ducky". However, I got a SIGSEGV error when I attempted to execute this program.

4.) Following the instructions that came with (3) I tried to get the source from https://svn.code.sf.net/p/glscene/code/branch but that URL does not seem to exist

**Comment by Kline777** [comment]
Hi!
Im using Delphi, but i could try to get it into lazarus and get back to you. If you want you could also install the free version of Delphi and install GLScene there
https://www.embarcadero.com/br/products/delphi/starter/promotional-download

Thank you for your help

**Comment by Kline777** [comment]
I've installed Lazarus and downloaded GLScene
I've Added the path in the CompilerOptions/Paths of a new project like you and then double clicked on GLSceneLCL_DesignTime.lpk

Then a window to install apears and i've done 'User'->'Install'. After that the IDE restarts and the components appear. I've compiled an example sucessfully.

**Comment by neurolabusc** [comment]
I did get some projects running (behaviors\torque, interfaces\simpleNavigation, meshes\CSG), while others compiled but crashed on launch or generated errors on compiling (e.g. the subdivide project generated an error at line 845 of GLCrossPlatform). However, with the programs that did run, I found they were very fragile, e.g. dropping a new button onto the panel of the CSG demo causes the program to crash when launching. I tried both the Intel and Nvidia GPU with the same results. In brief, GLScene does not seem stable enough on my system for development. However, I did take a look at the code and if you want to adapt my code I would suggest looking at the GLMeshOptimizer: the optimize mesh does allow simple mesh refinement (e.g. removing vertices that are near each other). I would have thought that those routines could be tuned to feed the face groups through the Fast Quadric simplification routines I have here. If you do make progress, I would be happy to include your samples into my project, or you could copy them to the GLScene project. GLScene does have a lot of nice features, so your efforts may help a lot of others.

**Comment by Kline777** [comment]
Some of the demos could require some other components instaled. I dont know about Lazarus but in Delphi GLscene is HIGHLY stable and realiable.

I will try some more. If i can get an example prepared in Lazarus i may come back to ask for your help again :)

Thank you

**Comment by neurolabusc** [comment]
Closing issue, no expertise with GLScene. Feel free to fork or provide pull requests as desired.
